<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>CtrlV</AssemblyName>
    <RootNamespace>CtrlV</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>CtrlV</Authors>
    <Description>YX剪贴板 - Windows 剪贴板管理器</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

</Project>